apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginxa
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: nginx.trn.cloudify.co
    http:
      paths:
      - path: /routea
        backend:
          serviceName: nginxa
          servicePort: 80